apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cesi-eats
spec:
  selector:
    app: rabbitmq-app
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
