name: Deploy - Prod

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helm Upgrade
        run: |
          helm upgrade rabbitmq-chart ./ --install --namespace cesi-eats --create-namespace
